"""@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file.
"""

import builtins
import typing

import google.protobuf.descriptor
import google.protobuf.message

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Record(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    DELETED_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.bytes
    timestamp: builtins.int
    deleted: builtins.bool
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: builtins.bytes = ...,
        timestamp: builtins.int = ...,
        deleted: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "deleted",
            b"deleted",
            "key",
            b"key",
            "timestamp",
            b"timestamp",
            "value",
            b"value",
        ],
    ) -> None: ...

global___Record = Record
